name: Build
on: [ push ]

jobs:
  build-spruceui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SpruceUI (fork) repository
        uses: actions/checkout@v3
        with:
          repository: 'StartsMercury/SpruceUI'
          ref: 'fork/1.20'
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish SpruceUI to Maven Local
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishToMavenLocal --stacktrace
      - name: Upload SpruceUI from maven local
        uses: actions/upload-artifact@v3
        with:
          name: SpruceUI Artifacts
          path: ~/.m2/repository/dev/lambdaurora/spruceui

  build:
    needs: build-spruceui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Download SpruceUI to maven local
        uses: actions/download-artifact@v2
        with:
          name: SpruceUI Artifacts
          path: ~/.m2/repository/dev/lambdaurora/spruceui
          retention-days: 1
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build --stacktrace
      - name: Capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
